extends:
  - '../../.eslintrc.yml'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'standard-jsx'
  - 'standard-react'
parserOptions:
  ecmaFeatures:
    jsx: true
env:
  browser: true
  node: true
  es6: true
  # jest: true
globals:
  __DEV__: true
rules:
  'no-use-before-define': 'off'
